name: spin2win_v2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.4
  cloud_functions: ^4.7.5
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.3
  url_launcher: ^6.2.6
  # State Management
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # ***** SECCIÓN DE ASSETS AÑADIDA *****
  assets:
    - assets/

  # ***** SECCIÓN DE FUENTES *****
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700