// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBznDgcHky7gUb_HQ2WQVWpcEr2P-bmZtU',
    appId: '1:100593458340:web:e68e7e53bd9351e61e1a31',
    messagingSenderId: '100593458340',
    projectId: 'spin2win-79023',
    authDomain: 'spin2win-79023.firebaseapp.com',
    storageBucket: 'spin2win-79023.firebasestorage.app',
    measurementId: 'G-VKVNP5ESSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvIpD0--YPqI9EPgDaTysPPSrX8NmicCY',
    appId: '1:965937832679:android:66e124c57f653104383842',
    messagingSenderId: '965937832679',
    projectId: 'spin2winv2',
    storageBucket: 'spin2winv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlUYFNby6noZDPBOxEFeP7Yd51eg55-Mg',
    appId: '1:100593458340:ios:3eab6c52b1a77dfe1e1a31',
    messagingSenderId: '100593458340',
    projectId: 'spin2win-79023',
    storageBucket: 'spin2win-79023.firebasestorage.app',
    androidClientId: '100593458340-76c0pvjith5c1k9dfvqe18k1omvdlvpp.apps.googleusercontent.com',
    iosClientId: '100593458340-gsv5ectn1b7fkpuvhrn39jm9tgef3lv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.spin2winV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlUYFNby6noZDPBOxEFeP7Yd51eg55-Mg',
    appId: '1:100593458340:ios:3eab6c52b1a77dfe1e1a31',
    messagingSenderId: '100593458340',
    projectId: 'spin2win-79023',
    storageBucket: 'spin2win-79023.firebasestorage.app',
    androidClientId: '100593458340-76c0pvjith5c1k9dfvqe18k1omvdlvpp.apps.googleusercontent.com',
    iosClientId: '100593458340-gsv5ectn1b7fkpuvhrn39jm9tgef3lv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.spin2winV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBznDgcHky7gUb_HQ2WQVWpcEr2P-bmZtU',
    appId: '1:100593458340:web:fcb99125c2c960e11e1a31',
    messagingSenderId: '100593458340',
    projectId: 'spin2win-79023',
    authDomain: 'spin2win-79023.firebaseapp.com',
    storageBucket: 'spin2win-79023.firebasestorage.app',
    measurementId: 'G-8MLJJKC9QL',
  );
}